import { agentRuns } from "./agent-run-store"
import type { AgentRun } from "./types"

const MOCK_RUNS: AgentRun[] = [
  {
    id: "mock-run-1",
    agentId: "inventory-agent",
    agentName: "Inventory Agent",
    task: "Show low stock items",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-1",
        toolName: "inventory.getLowStock",
        input: { threshold: 10 },
        output: { success: true, data: [{ name: "Steel Rod", stock: 3, minStock: 10 }] },
        status: "success" as const,
        startedAt: new Date(Date.now() - 60000),
        completedAt: new Date(Date.now() - 59500),
        durationMs: 500,
      },
    ],
    summary: "Found 3 items below minimum stock level. Steel Rod has only 3 units remaining (min: 10).",
    status: "completed",
    startedAt: new Date(Date.now() - 60000),
    completedAt: new Date(Date.now() - 59500),
    durationMs: 500,
  },
  {
    id: "mock-run-2",
    agentId: "sales-agent",
    agentName: "Sales Agent",
    task: "What's my recent order status?",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-2a",
        toolName: "orders.getActive",
        input: { limit: 5 },
        output: {
          success: true,
          data: [
            { number: "ORD-001", status: "processing", total: 15000 },
            { number: "ORD-002", status: "shipped", total: 28000 },
          ],
        },
        status: "success" as const,
        startedAt: new Date(Date.now() - 120000),
        completedAt: new Date(Date.now() - 118000),
        durationMs: 2000,
      },
      {
        id: "mock-step-2b",
        toolName: "customers.search",
        input: { query: "recent" },
        output: {
          success: true,
          data: [
            { name: "ABC Corp", orders: 12 },
            { name: "XYZ Ltd", orders: 8 },
          ],
        },
        status: "success" as const,
        startedAt: new Date(Date.now() - 117000),
        completedAt: new Date(Date.now() - 116000),
        durationMs: 1000,
      },
    ],
    summary: "You have 2 active orders: ORD-001 (processing, ฿15,000) and ORD-002 (shipped, ฿28,000). Top customer: ABC Corp with 12 orders.",
    status: "completed",
    startedAt: new Date(Date.now() - 120000),
    completedAt: new Date(Date.now() - 116000),
    durationMs: 4000,
  },
  {
    id: "mock-run-3",
    agentId: "finance-agent",
    agentName: "Finance Agent",
    task: "Show financial summary for this month",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-3",
        toolName: "finance.getSummary",
        input: { period: "month" },
        output: { success: true, data: { revenue: 450000, expenses: 320000, profit: 130000 } },
        status: "success" as const,
        startedAt: new Date(Date.now() - 300000),
        completedAt: new Date(Date.now() - 298000),
        durationMs: 2000,
      },
    ],
    summary: "Monthly financial summary: Revenue ฿450,000, Expenses ฿320,000, Net Profit ฿130,000.",
    status: "completed",
    startedAt: new Date(Date.now() - 300000),
    completedAt: new Date(Date.now() - 298000),
    durationMs: 2000,
  },
  {
    id: "mock-run-4",
    agentId: "inventory-agent",
    agentName: "Inventory Agent",
    task: "Forecast demand for next quarter",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-4a",
        toolName: "inventory.forecast",
        input: { productId: "prod-1", months: 3 },
        output: { success: true, data: { forecast: [120, 135, 150], confidence: 0.85 } },
        status: "success" as const,
        startedAt: new Date(Date.now() - 600000),
        completedAt: new Date(Date.now() - 597000),
        durationMs: 3000,
      },
    ],
    summary: "Forecast for next 3 months: 120, 135, 150 units (85% confidence). Consider increasing stock by 25%.",
    status: "completed",
    startedAt: new Date(Date.now() - 600000),
    completedAt: new Date(Date.now() - 597000),
    durationMs: 3000,
  },
  {
    id: "mock-run-5",
    agentId: "finance-agent",
    agentName: "Finance Agent",
    task: "Get outstanding invoices",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-5",
        toolName: "finance.getOutstanding",
        input: {},
        output: { success: false, error: { code: "API_ERROR", message: "Finance API temporarily unavailable" } },
        status: "error" as const,
        errorMessage: "Finance API temporarily unavailable",
        startedAt: new Date(Date.now() - 900000),
        completedAt: new Date(Date.now() - 898000),
        durationMs: 2000,
      },
    ],
    status: "failed",
    error: "Finance API temporarily unavailable",
    startedAt: new Date(Date.now() - 900000),
    completedAt: new Date(Date.now() - 898000),
    durationMs: 2000,
  },
  {
    id: "mock-run-6",
    agentId: "finance-agent",
    agentName: "Finance Agent",
    task: "Create invoice for ABC Corp for March services",
    context: {
      userId: "user-1",
      organizationId: "org-1",
      organizationSlug: "org-1",
      userRole: "admin",
      permissions: ["*"],
    },
    steps: [
      {
        id: "mock-step-6a",
        toolName: "customers.search",
        input: { query: "ABC Corp" },
        output: { success: true, data: [{ id: "cust-1", name: "ABC Corp" }] },
        status: "success" as const,
        startedAt: new Date(Date.now() - 1800000),
        completedAt: new Date(Date.now() - 1798000),
        durationMs: 2000,
      },
      {
        id: "mock-step-6b",
        toolName: "finance.createInvoice",
        input: { customerId: "cust-1", amount: 75000, description: "March consulting services" },
        status: "waiting_approval" as const,
        startedAt: new Date(Date.now() - 1795000),
      },
    ],
    status: "waiting_approval",
    approvalRequest: {
      id: "approval-1",
      toolName: "finance.createInvoice",
      input: { customerId: "cust-1", amount: 75000, description: "March consulting services" },
      reason: 'Tool "finance.createInvoice" requires approval before execution',
      status: "pending",
      requestedBy: "user-1",
      requestedAt: new Date(Date.now() - 1795000),
    },
    startedAt: new Date(Date.now() - 1800000),
    durationMs: 5000,
  },
]

export function seedMockAgentRuns() {
  if (agentRuns.length === 0) {
    agentRuns.push(...MOCK_RUNS)
  }
}
